// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Busqueda', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Busqueda', async function() {
    await driver.get("http://bancoalimentario.org.ar/")
    await driver.findElement(By.name("s")).sendKeys("luis mariano")
    await driver.findElement(By.css("#search-4 .search-icon")).click()
  })
})
